// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDt1EaJhmQAQ9knAykgtZGuR52o80GmA4g',
    appId: '1:144445685259:web:519208b5621ed905ad110e',
    messagingSenderId: '144445685259',
    projectId: 'simplequeue-1010f',
    authDomain: 'simplequeue-1010f.firebaseapp.com',
    storageBucket: 'simplequeue-1010f.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA1jqxgUpH54u_QQgMu-QStIk0dZtAZsQU',
    appId: '1:144445685259:android:3453ede2d0a3aa95ad110e',
    messagingSenderId: '144445685259',
    projectId: 'simplequeue-1010f',
    storageBucket: 'simplequeue-1010f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBgtmix07q6KFsaNBn446-ytIx2EhOVgag',
    appId: '1:144445685259:ios:0ffdc641f82850f7ad110e',
    messagingSenderId: '144445685259',
    projectId: 'simplequeue-1010f',
    storageBucket: 'simplequeue-1010f.appspot.com',
    iosBundleId: 'com.example.simpleQueue',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBgtmix07q6KFsaNBn446-ytIx2EhOVgag',
    appId: '1:144445685259:ios:0c056743e6d07ea7ad110e',
    messagingSenderId: '144445685259',
    projectId: 'simplequeue-1010f',
    storageBucket: 'simplequeue-1010f.appspot.com',
    iosBundleId: 'com.example.simpleQueue.RunnerTests',
  );
}
